site_name: ğŸŠ-ECC
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
  icon:
    logo: material/format-list-checks
  palette:
    primary: orange

nav:
  - ä¸»é¡µ: index.md
  - ECC:
    - Git: ecc/git.md
  - çŒ«å’ªè¯å…¸:
    - å¯¼è§ˆ: dict/index.md
    - FPGA ç›¸å…³: dict/fpga.md

extra_css:
  - styles/index.css
