site_name: ğŸŠ-ECC
repo_url: https://github.com/thu-cs-lab/Orange-ECC
repo_name: Orange-ECC

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
  icon:
    logo: material/format-list-checks
  palette:
    primary: orange

nav:
  - ä¸»é¡µ: index.md
  - ä½¿ç”¨æ–¹æ³•: meta.md
  - ECC:
    - Git: ecc/git.md
    - Linux: ecc/linux.md
    - Vim: ecc/vim.md
  - çŒ«å’ªè¯å…¸:
    - å¯¼è§ˆ: dict/index.md
    - FPGA ç›¸å…³: dict/fpga.md
    - ç½‘ç»œç›¸å…³: dict/networking.md
    - Linux ä½¿ç”¨ç›¸å…³: dict/linux.md

extra_css:
  - styles/index.css

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
