site_name: ğŸŠ-ECC
theme:
  name: material
  features:
    - instant
    - tabs
  icon:
    logo: material/format-list-checks
  palette:
    primary: orange

nav:
  - ä¸»é¡µ: index.md
  - çŒ«å’ªè¯å…¸:
    - è¯å…¸ç´¢å¼•: dict/index.md
    - FPGA ç›¸å…³: dict/fpga.md
